feat: add solution to leetcode No.0033 No.0081
doocs/leetcode pull request #355
Opened 2021-04-07 15:25 UTC by Moriarty12138

2021-04-07 15:47 UTC, yanglbme requested changes

2021-04-07 15:47 UTC, yanglbme commented on solution/0000-0099/0081.Search in Rotated Sorted Array II/README.md
> +		bool search(vector<int>& nums, int target) {
这里代码格式有问题，缩进异常。

2021-04-07 15:50 UTC, yanglbme commented on solution/0000-0099/0081.Search in Rotated Sorted Array II/README.md
> +		bool search(vector<int>& nums, int target) {
我先帮你合一下吧，然后做下格式调整，下次注意一下格式问题哈

2021-04-07 15:51 UTC, merged

2021-04-07 22:18 UTC, Moriarty12138 commented on solution/0000-0099/0081.Search in Rotated Sorted Array II/README.md
> +		bool search(vector<int>& nums, int target) {
- okok

2021-04-08 00:29 UTC, yanglbme commented on solution/0000-0099/0081.Search in Rotated Sorted Array II/README.md
> +		bool search(vector<int>& nums, int target) {
之后的代码提交不注明 author 哈，git 已经记录了作者了