quicksort， cpp version
doocs/leetcode pull request #558
Opened 2021-09-13 08:42 UTC by rongliang666

quicksort， cpp version

2021-09-13 09:12 UTC, yanglbme requested changes

2021-09-13 09:12 UTC, yanglbme commented on basic/sorting/QuickSort/README.md
> +```c++
```suggestion
```cpp
```

2021-09-13 09:12 UTC, yanglbme commented on basic/sorting/QuickSort/README.md
> +**C++**
```suggestion
### **C++**
```

2021-09-14 03:28 UTC, rongliang666 commented on basic/sorting/QuickSort/README.md
> +```c++
修改后重新pr，这个老的是关闭，貌似我没权限操作老的?

2021-09-14 03:37 UTC, closed without merging