feat: add php solution to lc problem: No.s0100
doocs/leetcode pull request #932
Opened 2023-03-14 12:49 UTC by Qiu-IT

第100题 php解法 谢谢

2023-03-14 16:04 UTC, YangFong requested changes

2023-03-14 16:04 UTC, YangFong commented on solution/0100-0199/0100.Same Tree/Solution.php
> +        return $this - > isSameTree($p - > left, $q - > left) && $this - > isSameTree($p - > right, $q - > right);
注意 `- >`，需修正为 `->`。README 也要同步修改

2023-03-14 16:04 UTC, YangFong commented on solution/0100-0199/0100.Same Tree/README.md
> +### **PHP**
标题上一行需要留空，EN 版本也是如此

2023-03-14 16:38 UTC, Qiu-IT commented
已修改 下次同类型问题要好好注意 
谢谢您们

2023-03-15 02:58 UTC, YangFong requested changes

2023-03-15 02:58 UTC, YangFong commented on solution/0100-0199/0100.Same Tree/Solution.php
> +        return $this -> isSameTree($p -> left, $q -> left) && $this -> isSameTree($p -> right, $q -> right);
虽然支持 `$this -> propsName` 这种写法，但推荐使用 `$this->propsName` 形式（箭头左右不加空白，可参考该文件 8~10 行注释）。

```suggestion 
        if ($p->val != $q->val) {
            return false;
        }
        return $this->isSameTree($p->left, $q->left) && $this->isSameTree($p->right, $q->right);
```

2023-03-16 09:49 UTC, Qiu-IT commented
回复晚了 谢谢你的提醒

2023-03-16 11:02 UTC, yanglbme approved these changes

2023-03-16 11:03 UTC, merged